const mongoose = require('mongoose');
const env = require('../config/env');
const { Complaint } = require('../models/Complaint');
const Event = require('../models/Event');
const { syncComplaintFeedStatus } = require('../services/complaintService');

async function migrate() {
  await mongoose.connect(env.mongoUri);
  console.log('[Migration] Connected to MongoDB.');

  // 1. Identify the user's manually submitted complaint
  // User submitted Jaipur road_damage with description 'fsdss'
  const userComplaint = await Complaint.findOne({
    city: 'Jaipur',
    description: /fsdss/i
  });

  if (userComplaint) {
    console.log(`[Migration] Found user's manual complaint: ID=${userComplaint._id}, desc="${userComplaint.description}"`);
    await Complaint.updateOne(
      { _id: userComplaint._id },
      {
        $set: {
          source: 'citizen',
          synthetic: false,
          isSynthetic: false,
          isReal: true
        }
      }
    );

    // Update corresponding event
    await Event.updateMany(
      { 'metadata.complaintId': userComplaint._id },
      {
        $set: {
          source: 'citizen',
          synthetic: false,
          isSynthetic: false,
          isReal: true
        }
      }
    );
    console.log(`[Migration] Marked user's manual complaint and its event as REAL (source="citizen", synthetic=false, isReal=true).`);
  } else {
    console.warn(`[Migration] User complaint with description 'fsdss' not found directly. Checking for manual submissions...`);
  }

  // 2. All other complaints were auto-generated by scripts/subagents
  const otherComplaintsFilter = userComplaint ? { _id: { $ne: userComplaint._id } } : {};
  const otherComplaintsResult = await Complaint.updateMany(
    otherComplaintsFilter,
    {
      $set: {
        source: 'demo',
        synthetic: true,
        isSynthetic: true,
        isReal: false
      }
    }
  );
  console.log(`[Migration] Updated ${otherComplaintsResult.modifiedCount} auto-generated complaint(s) to SIMULATED (source="demo", synthetic=true, isReal=false).`);

  // 3. Update all other complaint events in Event collection
  const otherEventsFilter = userComplaint
    ? {
        source: { $in: ['complaint', 'citizen', 'demo'] },
        'metadata.complaintId': { $ne: userComplaint._id }
      }
    : { source: { $in: ['complaint', 'citizen', 'demo'] } };

  const otherEventsResult = await Event.updateMany(
    otherEventsFilter,
    {
      $set: {
        source: 'demo',
        synthetic: true,
        isSynthetic: true,
        isReal: false
      }
    }
  );
  console.log(`[Migration] Updated ${otherEventsResult.modifiedCount} complaint event(s) to SIMULATED (source="demo", synthetic=true, isReal=false).`);

  // 4. Sync FeedStatus
  await syncComplaintFeedStatus();
  console.log('[Migration] Synced complaint FeedStatus.');

  await mongoose.disconnect();
  console.log('[Migration] Completed successfully.');
}

migrate().catch(console.error);
